### ISSUE TITLE
Support XML Namespaces in Writer

### ISSUE THREAD

**Issue by MFAshby** [ianprime0509/zig-xml#40]
Related to https://github.com/ianprime0509/zig-xml/issues/10

Currently the Writer API does not explicitly support namespaces. 

It's possible to mostly work around it by adding the appropriate XML attributes: 
```zig
    fn write(self: Multistatus, wtr: *xml.Writer, a: std.mem.Allocator) !void {
        try wtr.elementStart("multistatus");
        try wtr.attribute("xmlns", "DAV:");
        try wtr.attribute("xmlns:c", "urn:ietf:params:xml:ns:carddav");
...
```

however, this means it's now down to the library user to track which namespace prefix is used for which namespace and specify element names with the appropriate prefix in child nodes. The prefix has [no meaning except to identify the namespace](https://www.w3.org/TR/xml-names/#NT-PrefixedName). 

Ideally the writer API would handle this for us; when calling `Writer.elementStart` there should be an option to specify the _namespace_ of the current element; as well as optionally setting the current default and non-default namespaces. The writer could handle assigning prefixes to namespaces.

**Comment by ianprime0509** [comment]
I think allowing the namespace prefix to be auto-generated is a good idea, although I would also like to allow optionally assigning a custom prefix to the namespace, to support a more human-readable output format for cases where certain namespaces have conventional prefixes. What I'm starting on to make more progress towards #10 is planned to look something like this:

- `writer.bindNs("ns", "http://example.com")` - binds a namespace prefix (inside an `element_start`, this will emit an `xmlns:ns` attribute; otherwise, it will store it in a "pending" list to be bound the next time an element is started, which is required to handle a case like `<ns:local xmlns:ns="...">...`)
- `writer.elementStart("ns:local")` - works the same as it does now
- `writer.elementStartNs("http://example.com", "local")` - looks up the bound (or pending) namespace prefix for `http://example.com` and uses it, or makes up and binds a new one if there isn't one already
- `writer.attribute("ns:local", "text")` - works the same as it does now
  - `writer.attribute("xmlns", "http://example.com")` or `writer.attribute("xmlns:ns", "http://example.com")` - additionally keeps track of the new namespace binding
- `writer.attributeNs("http://example.com", "local", "text")` - does the same sort of processing as `elementStartNs`

(just as `Reader` has a `namespace_aware` option currently which can be set to false to disable namespace processing, `Writer` will also get the same option, making all the `Ns`-suffixed functions illegal and skipping any extra namespace processing of elements and attributes)

Another goal of #10 is to have configurable safety checks which should ideally be able to catch any well-formedness errors when using any of these functions, but that's a longer term goal and I don't think I'll include that in the initial implementation of this.

**Comment by MFAshby** [comment]
that sounds great :D 

I've hacked something together [here](https://github.com/ianprime0509/zig-xml/compare/main...MFAshby:zig-xml:ns_writer?expand=1) which allows introducing namespaces and applying namespaces to element names (not attributes yet) with elementStartNs. It generates prefixes for you but doesn't yet allow user-supplied ones. I'll tweak it a bit and see if I can bring it into line with your suggested API.

**Comment by ianprime0509** [comment]
Thanks! I actually have an initial version locally, where I'm also planning to fill out the test suite and doc comments, but it'll likely be a few days until it's completely ready, though.

**Comment by ianprime0509** [comment]
I opened #41 with an initial implementation of the API outlined above. All the tests I added are passing, but I'm going to take another look at it later before merging to make sure I didn't miss anything.
